# Generated by Django 3.1.7 on 2021-03-26 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_like_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='like_users',
            new_name='liked_users',
        ),
    ]
