# Generated by Django 3.1.7 on 2021-03-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='body',
            new_name='title',
        ),
        migrations.AddField(
            model_name='video',
            name='video_key',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
