# Generated by Django 3.1.7 on 2021-03-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_video_video_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_image',
            field=models.ImageField(null=True, upload_to='videos'),
        ),
    ]
