# Generated by Django 3.1.7 on 2021-03-26 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20210326_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_image',
            field=models.ImageField(null=True, upload_to='posts'),
        ),
    ]
