# Generated by Django 3.1.7 on 2021-03-29 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20210326_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_image',
            field=models.ImageField(null=True, upload_to='videos'),
        ),
    ]
