# Generated by Django 3.1.7 on 2021-03-29 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_post_post_hit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_hit',
            new_name='n_hit',
        ),
    ]
