# Generated by Django 3.1.7 on 2021-03-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_auto_20210329_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='v_hit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
