# Generated by Django 3.1.7 on 2021-03-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_video_v_hit'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
