# Generated by Django 3.1.7 on 2021-03-29 09:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0020_video_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='v_liked_users',
            field=models.ManyToManyField(related_name='v_liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
