# Generated by Django 3.1.7 on 2021-03-29 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_video_v_liked_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='v_liked_users',
        ),
    ]
