# Generated by Django 3.1.7 on 2021-03-30 06:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0022_remove_video_v_liked_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='vliked_users',
            field=models.ManyToManyField(related_name='vliked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
