# Generated by Django 3.1.7 on 2021-03-30 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0028_comment_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
    ]
